## 1. Numpy
### 1.1 Numpy 배열

In [1]:
import numpy as np

- numpy n-dim array(ndarray) vs list

In [4]:
l =[1, 2, 3, 4, 5]
l * 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
# numpy array (백터화 연산)
n = np.array([1,2,3,4,5])
n * 2


array([ 2,  4,  6,  8, 10])

In [6]:
# 모든 수의 제곱수
[i * i for i in l]

[1, 4, 9, 16, 25]

In [8]:
np.square(n) # square <= (array임 , 파라메터로 array 를 주면 백터화 연산을 한다.산술 연산화를 하기 위해...)

array([ 1,  4,  9, 16, 25])

- 1차원 배열(백터 Vector)

In [10]:
a = np.array((1, 2, 3, 4, 5))       # ()안에 넣으면 튜플, []안에 넣으면 리스트
type(a)


numpy.ndarray

In [12]:
a.dtype, a.shape, a.ndim, a.size  # a의 데이터 타입, a의 형태 튜플일 땐 ( , )콤마를 써줘야함 , a의 차원, a의 크기

(dtype('int32'), (5,), 1, 5)

In [13]:
# 백터화 연산을 지원해준다.
a * 2

array([ 2,  4,  6,  8, 10])

In [15]:
b = np.array([10, 20, 30, 40, 50])
c = 2 * a +b
c

array([12, 24, 36, 48, 60])

In [16]:
a == 2      # 맨 위에 a = 1, 2, 3, 4, 5

array([False,  True, False, False, False])

In [17]:
b > 20

array([False, False,  True,  True,  True])

- 2차원 배열(Matrix)

In [38]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c = np.arange(1, 7).reshape(2,3)      # arange: 파이썬의 range와 동일한 기능
c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
c.dtype, c.shape, c.ndim, c.size        # (dtype('테이터타입'), (행렬), 차원, 크기(갯수))

(dtype('int32'), (6,), 1, 6)

- 3차원 배열(Tensor)

In [23]:
d = np.arange(1, 25).reshape(2, 3, 4)       # reshape(plane, row, column)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [24]:
d.dtype, d.shape, d.ndim, d.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [25]:
a

array([1, 2, 3, 4, 5])

In [26]:
a[0], a[3], a[-1]

(1, 4, 5)

In [27]:
c

array([1, 2, 3, 4, 5, 6])

In [39]:
c[0][0], c[0, 0]

(1, 1)

In [40]:
c[1, 0], c[0, -1], c[-1, -1]

(4, 3, 6)

In [30]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [31]:
# 9, 20
d[0, -1, 0], d[-1, 1, -1]

(9, 20)

- 배열의 슬라이싱


In [32]:
# 라스트에서는 행, 열 슬라이싱이 동시에 안됨 
l = [[1,2,3], [4,5,6], [7,8,9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [34]:
# 엉뚱한 결과가 나옴
l[:2][:2]          # 원래는 [[1,2]], [[4,5]]

[[1, 2, 3], [4, 5, 6]]

In [33]:
l[1][:2]

[4, 5]

In [44]:
c = np.arange(1, 13).reshape(3, 4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# 위 두 행
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# 오른쪽 두 열
c[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [47]:
# 2, 3, 6, 7
c[:-1, 1:3]

array([[2, 3],
       [6, 7]])

In [48]:
#1, 3, 5, 7
c[:2, ::2]

array([[1, 3],
       [5, 7]])

In [55]:
# 연습문제 

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

14

In [ ]:
# 이 행렬에서 값 7을 인덱싱한다.
m[1,2]

In [ ]:
#이 행렬에서 값 14 을 인덱싱한다
m[2,4]

In [63]:
#이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]

array([6, 7])

In [68]:
#이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[[1,2],[2,2]]

array([ 7, 12])

In [73]:
#이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [74]:
# 맨 마지막 열이 y, 나머지는 X
X = m[:, :-1]       # X가 대문자인 이유 2차원
y = m[:, -1]        # y가 소문자인 이유 1차원
                    # 차원이 작은쪽이 소문자로 표시한다.

- 배열 인덱싱(Fancy indexing)

In [79]:
# idx 값이 True/False이면, True 값이 있는 곳의 원소만 통과(Filter)
print(a)
idx = np.array([True, False, True, True, False])
print(a[idx])

[1 2 3 4 5]
[1 3 4]


In [80]:
# 홀수만 통과
a[a % 2 == 1 ]

array([1, 3, 5])

In [81]:
# 3보다 큰 수만 통화
a[a > 3]

array([4, 5])

In [83]:
# idx 값이 정수(인덱스)면 해당 인덱스의 원소가 선택됨
idx = np.array([1, 2, 4])
a[idx]

array([2, 3, 5])

In [87]:
# 연습문제 
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
# 이 배열에서 3의 배수를 찾아라.
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [90]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [91]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [93]:
# 위의 결과는 ndarray. 원소의 값을 끄집어 내려면 다시 인덱싱 해주어야 함 
x[(x % 3 == 0) & (x % 4 == 1)][0]

9