### 1.3 배열의 연산 (Operation)

In [1]:
import numpy as np

- 백터화 연산


In [2]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [6]:
%%time 
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i] 

CPU times: total: 93.8 ms
Wall time: 73 ms


In [8]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [10]:
a >= b

array([False,  True,  True,  True])

In [11]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [12]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [13]:
5 * a

array([ 5, 10, 15, 20])

In [14]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [15]:
x = np.arange(1, 5)
np.sum(x)

10

In [16]:
x.sum()

10

In [19]:
x.min(), x.max(), x.mean() # 최소, 최대, 평균 ( list에선 안되지만 배열에선 가능 )

(1, 4, 2.5)

In [20]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [21]:
# 통계: 분산, 표준편자
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [23]:
# 최소값, 최대값의 인덱스
x.argmin(), x.argmax()

(0, 3)

- all/any

In [24]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [25]:
np.all(a == a)

True

axis0 -> 행 ( 행에 있는 첫번째 인덱스가 움직인다. )

axis1 -> 열 ( 열에 있는 첫번째 인덱스가 움직인다. )

헷갈리니까 예시를 보고 해보긔 

- 2차원 이상의 연산

In [26]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# 모든 원소의 합
np.sum(a), np.mean(a)

(21, 3.5)

In [29]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 엑세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [30]:
# axis = 0, 각 좌표(row, col)에서  col를 변경시켜가면서 엑세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [31]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [33]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [34]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [63]:
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
np.random.seed = 2023
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[7.9194, 6.3014, 1.1785, 6.1873, 2.0681, 4.7071],
       [4.0639, 7.7541, 3.2482, 2.2784, 2.5637, 8.2956],
       [6.818 , 6.7544, 2.105 , 5.9883, 4.1456, 8.0261],
       [6.2484, 7.1892, 7.7847, 1.2256, 8.0799, 4.5882],
       [1.9959, 2.8748, 8.5294, 4.3648, 5.4826, 3.8482]])

In [56]:
# 전체의 최댓값
np.max(x)

9.9241

In [57]:
# 각 행의 합
np.sum(x, axis=1)

array([28.9213, 30.141 , 44.7408, 22.4351, 31.9852])

In [58]:
# 각 행의 최댓값
np.max(x, axis=1)

array([8.4386, 9.0814, 9.4437, 8.6575, 9.9241])

In [60]:
# 각 열의 평균
np.mean(x, axis=0)

array([4.96926, 5.819  , 4.65998, 7.07368, 4.20694, 4.91582])

In [62]:
# 각 열의 최솟값
np.min(x, axis=0)

array([1.5931, 0.8932, 0.4632, 2.658 , 2.2773, 2.1373])

- 정렬(sort)

In [66]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [68]:
np.sort(a)   # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [69]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [71]:
# 내림차순 정렬, axis=1일 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [74]:
# 올림차순 정렬, axis=1일 경우
np.sort(a, axis=1)[::-1, :]

array([[ 1,  2, 14, 15],
       [ 1,  9, 11, 12],
       [ 3,  4,  5,  7]])

In [75]:
# 내림차순 정렬, axis=0인 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [76]:
# sort() method는 자기 파괴적(in-place) method
a.sort(axis=1)