### 1.3 배열의 연산 (Operation)

In [57]:
import numpy as np

- 백터화 연산


In [58]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [59]:
%%time 
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i] 

CPU times: total: 78.1 ms
Wall time: 78.5 ms


In [60]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [61]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [62]:
a >= b

array([False,  True,  True,  True])

In [63]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [64]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [65]:
5 * a

array([ 5, 10, 15, 20])

In [66]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [67]:
x = np.arange(1, 5)
np.sum(x)

10

In [68]:
x.sum()

10

In [69]:
x.min(), x.max(), x.mean() # 최소, 최대, 평균 ( list에선 안되지만 배열에선 가능 )

(1, 4, 2.5)

In [70]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [71]:
# 통계: 분산, 표준편자
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [72]:
# 최소값, 최대값의 인덱스
x.argmin(), x.argmax()

(0, 3)

- all/any

In [73]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [74]:
np.all(a == a)

True

axis0 ->  ( 행에 있는 첫번째 인덱스가 움직인다. 그렇다고 행은 아님 )

axis1 -> ( 열에 있는 첫번째 인덱스가 움직인다. 그렇다고 열은 아님 )

헷갈리니까 예시를 보고 해보긔 

- 2차원 이상의 연산

In [75]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
# 모든 원소의 합
np.sum(a), np.mean(a)

(21, 3.5)

In [77]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 엑세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [78]:
# axis = 0, 각 좌표(row, col)에서  col를 변경시켜가면서 엑세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [79]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [81]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [82]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [83]:
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
np.random.seed(2023)
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

TypeError: 'int' object is not callable

In [ ]:
# 전체의 최댓값
np.max(x)

9.1826

In [ ]:
# 각 행의 합
np.sum(x, axis=1)

array([22.1716, 30.2422, 38.1811, 22.9968, 34.3235])

In [ ]:
# 각 행의 최댓값
np.max(x, axis=1)

array([7.0754, 8.6949, 9.1025, 7.8241, 9.1826])

In [ ]:
# 각 열의 평균
np.mean(x, axis=0)

array([4.4277 , 6.7592 , 4.29722, 5.02308, 3.04106, 6.03478])

In [ ]:
# 각 열의 최솟값
np.min(x, axis=0)

array([0.5289, 4.8481, 2.3753, 0.5885, 0.2719, 2.7361])

- 정렬(sort)

In [ ]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [ ]:
np.sort(a)   # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [ ]:
# 내림차순 정렬, axis=1일 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [ ]:
# 올림차순 정렬, axis=1일 경우
np.sort(a, axis=1)[::-1, :]

array([[ 1,  2, 14, 15],
       [ 1,  9, 11, 12],
       [ 3,  4,  5,  7]])

In [ ]:
# 내림차순 정렬, axis=0인 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [ ]:
# sort() method는 자기 파괴적(in-place) method
a.sort(axis=1)

In [ ]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [ ]:
a[j]

array([12, 25, 38, 42])

- 연습문제 3.3.2
    - 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

In [ ]:
score = np.array([[  1,    2,    3,    4],
                  [ 46,   99,  100,   71],
                  [ 81,   59,   90,  100]])

score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
# 영어 성적을 argsort() 하여 인덱스를 구함
indices = np.argsort(score[1])          # [ 46, 99, 100, 71]을 올림 차순 순으로 두고 그 인덱스를 나열.
indices

array([0, 3, 1, 2], dtype=int64)

In [ ]:
# 인덱스를 내림차순으로 정렬
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [ ]:
# 모든 행을 영어 성적 내림차순으로 정렬
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])