### 1.5 난수 발생과 카운팅

In [44]:
import numpy as np

- 시드 설정

In [45]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [46]:
x = np.arange(10)
np.random.shuffle(x)        # x 데이터의 순서를 바꿈
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링

In [47]:
np.random.choice(5, 5, replace=False)       # replace 중복 허용 
                                            # 비복원 추출

array([3, 4, 0, 2, 1])

In [48]:
np.random.choice(5, 5, replace=True)        # 복원 추출

array([1, 0, 2, 3, 0])

In [49]:
x = np.random.randint(1, 100, 10)       # 1 <= x < 100
x

array([30, 50, 50, 50, 50, 54, 39, 71, 16, 89])

In [50]:
np.random.choice(x, 5, replace=False)

array([30, 50, 50, 71, 89])

- 난수 생성

In [51]:
# random() - Uniform 분포, 무조건 0 ~ 1 사이의 값만 나옴
np.random.random(10)

array([0.09702613, 0.81625998, 0.02808046, 0.01545164, 0.56690572,
       0.59310305, 0.9147945 , 0.25066314, 0.07173657, 0.30121014])

In [52]:
# randont(low, high, N) - [low, high] 범위의 정수 N 개
np.random.randint(1, 7, 10)

array([5, 4, 4, 1, 6, 4, 2, 6, 3, 4])

In [53]:
# normal(평균, 표준편차, N) - 정규분포 N개
np.random.normal(170, 10, 10)

array([156.89599302, 176.76839882, 158.92016878, 184.48954679,
       159.75379517, 180.52417547, 177.7632241 , 178.26794973,
       172.40028585, 188.98243469])

In [54]:
# randn - 표준 정규분포 N(0, 1) N개
np.random.randn(10)

array([ 0.36683324,  0.81473231,  0.07235438,  0.6012461 , -1.727901  ,
        0.23404311, -0.01310212, -1.44489043, -1.29733638, -2.03158937])

In [55]:
# binomial(시도횟수, 평균, N) - 이항분포 B(N, P)
np.random.binomial(10,0.5,20).reshape(4,5)      # ex) 동전을 10번 던저서 앞,뒤 나올 확률이 20번?

array([[8, 7, 2, 4, 6],
       [4, 3, 6, 4, 5],
       [2, 4, 6, 7, 2],
       [6, 6, 5, 6, 5]])

In [56]:
# 가설검정: t-점겅 (1-sample T, 2-sample T, paired T)
# Standard t(자유도, N)
np.random.standard_t(2, 10)

array([-0.53206837, -0.22784308, -2.06707851,  0.97846344,  1.03677625,
       -1.63268272, -0.9087145 ,  3.46933835, -0.46213729, -0.21273215])

- 연습문제 3.5.1
- 1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
- 2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.  

In [57]:
# 1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(10, 0.5, 10)

array([2, 6, 4, 3, 6, 5, 5, 2, 8, 7])

In [58]:
# 2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라
dice = np.random.randint(1, 7, 100)
np.mean(dice)

3.24

- 연습문제 3.5.2
- 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [59]:
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
# 250일 동안의 주가를 무작위로 생성하라
# 5개만 먼저 테스트

rate = np.random.normal(0, 0.01, 5)
rate                     # 퍼센트 단위 출력

array([-0.00251966, -0.00657709, -0.01101067,  0.0167215 , -0.00373628])

In [60]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])   # price * (1 + r)
    price = int(round(price, 0))    # 가격의 단위는 원(소숫점 아래 자리는 버림)
    print(price, end=' ')

9975 9909 9800 9964 9927 

In [61]:
# 250개의 수익률 생성
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [62]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0))
    price_list.append(price)

price_list[-10:]

[10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691, 10497]

In [63]:
# 2. 어레이로 해결
price = 10000
price_array = np.empty(250, dtype=int)
for i in range(250):
       price = price * (1 + rate[i])
       price = int(round(price, 0))
       price_array[i] = price

price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [64]:
np.random.seed(2023)
dices = np.random.randint(1, 7, 100)

In [65]:
# 고유한 값
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [66]:
# 고유한 값과 돗수
np.unique(dices, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([16, 18, 13, 15, 19, 19], dtype=int64))

In [67]:
indices,count = np.unique(dice, return_counts=True)
indices * count

array([22, 36, 48, 60, 80, 78], dtype=int64)

In [68]:
# 가중 평균
np.sum(indices * count) / np.sum(count)

3.24

In [69]:
np.mean(dices)

3.6

In [70]:
a = np.array(['x', 'y', 'x', 'y', 'z', 'y'])
np.unique(a, return_counts=True)

(array(['x', 'y', 'z'], dtype='<U1'), array([2, 3, 1], dtype=int64))